---
- name: update apt packages
  become: true
  apt:
    update_cache: true

- name: upgrade packages
  become: true
  apt:
    upgrade: yes

- name: "install python for Ansible."
  become: true
  apt:
    name: python3

- name: install node
  become: true
  apt:
    name: nodejs

- name: install npm
  become: true
  apt:
    name: npm

- name: install pm2
  become: true
  npm:
    name: pm2
    global: true

- name: get node exporter package
  become: true
  get:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz

- name: extract node exporter package
  become: true
  shell: tar xzf node_exporter-1.0.1.linux-amd64.tar.gz

- name: start node exporter
  become: true
  shell: |
    cd node_exporter-1.0.1.linux-amd64
    ./node_exporter