---
- name: create web dir
  file:
    state: directory
    path: ~/udapeople

- name: copy backend application
  copy:
    src: artifact.tar.gz
    dest: ~/udapeople/artifact.tar.gz

- name: unzip tar bundle
  shell: tar -xvzf ~/udapeople/artifact.tar.gz -C ~/udapeople

- name: init pm2
  shell:
    cmd: |
      pm2 --help

- name: Start app
  shell:
    cmd: |
      cd ~/udapeople
      npm install
      pm2 stop default
      pm2 start npm -- start

- name: start node exporter
  become: true
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter      
    